import os

YOUTUBE_DEVELOPER_KEY = os.environ['YOUTUBE_DEVELOPER_KEY']
YOUTUBE_CHANNEL_ID = os.environ['YOUTUBE_CHANNEL_ID']
YOUTUBE_VIDEO_COUNT_SLACK_TOKEN = os.environ['YOUTUBE_VIDEO_COUNT_SLACK_TOKEN']
YOUTUBE_SUBS_SLACK_TOKEN = os.environ['YOUTUBE_SUBS_SLACK_TOKEN']
YOUTUBE_CHANNEL_COUNT_SLACK_TOKEN = os.environ['YOUTUBE_CHANNEL_COUNT_SLACK_TOKEN']
FACEBOOK_ACCESS_TOKEN = os.environ['FACEBOOK_ACCESS_TOKEN']
FACEBOOK_PAGE_ID = os.environ['FACEBOOK_PAGE_ID']
FACEBOOK_SLACK_TOKEN = os.environ['FACEBOOK_SLACK_TOKEN']
SLACK_TEAM_ID = os.environ['SLACK_TEAM_ID']
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"