import os

DEVELOPER_KEY = os.environ['DEVELOPER_KEY']
CHANNEL_ID = os.environ['CHANNEL_ID']
COUNT_TOKEN = os.environ['COUNT_TOKEN']
SUBS_TOKEN = os.environ['SUBS_TOKEN']
CHANNEL_COUNT_TOKEN = os.environ['CHANNEL_COUNT_TOKEN']
TEAM_ID = os.environ['TEAM_ID']
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"